spring.data.mongodb.uri=mongodb://localhost:27017/product_db
spring.data.mongodb.database=product_db

# Logging
spring.main.banner-mode=console

# 404 error configuration to catch it in GlobalExceptionHandler
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# DB Debugging: Bật log để soi câu lệnh MongoDB (Chỉ hiện câu lệnh nghiệp vụ)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=INFO

# MQTT Configuration
mqtt.broker-url=tcp://localhost:1883
mqtt.client-id=spring-backend-001
mqtt.username=admin
mqtt.password=public
mqtt.default-topic=iot/v1/tenant1/qrbox/+/evt
